export const LOGIN_SERVICE = Symbol('LOGIN_SERVICE');
export const EXTRACT_USER_SERVICE = Symbol('EXTRACT_USER_SERVICE');
export const REFRESH_TOKEN_SERVICE = Symbol('REFRESH_TOKEN_SERVICE');
export const JWT_TOKEN_SERVICE = Symbol('JWT_TOKEN_SERVICE');
export const ENCRYPTION_SERVICE = Symbol('ENCRYPTION_SERVICE');
